# Generated by Django 3.0.8 on 2020-08-19 04:47

from django.db import migrations, models
import frontoffice.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitorbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('id_card', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('in_time', models.TimeField(blank=True, null=True)),
                ('out_time', models.TimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='visitorbook', validators=[frontoffice.models.validate_file])),
                ('image', models.ImageField(null=True, upload_to='visitorbook', validators=[frontoffice.models.validate_image])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
