# Generated by Django 3.0.8 on 2020-08-19 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0002_status_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
