# Generated by Django 3.0.8 on 2020-08-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0004_auto_20200819_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phonecall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('call_duration', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(null=True)),
                ('followup', models.DateField(blank=True, null=True)),
                ('call_type', models.IntegerField(choices=[(1, 'Incoming'), (2, 'Outgoing')], null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='visitorbook',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='visitorbook',
            name='in_time',
            field=models.TimeField(null=True),
        ),
    ]
