# Generated by Django 3.0.8 on 2020-08-19 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0005_auto_20200819_1744'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phonecall',
            new_name='Phonecalllog',
        ),
    ]
