# Generated by Django 3.0.8 on 2020-08-20 03:36

from django.db import migrations, models
import frontoffice.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0007_postaldispatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postalreceive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=200, null=True)),
                ('sender', models.CharField(max_length=200, null=True)),
                ('referance', models.CharField(max_length=200, null=True)),
                ('receive_date', models.DateField(null=True)),
                ('address', models.TextField(null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='postal', validators=[frontoffice.models.validate_file])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='postaldispatch',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
