# Generated by Django 3.0.8 on 2020-08-20 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import frontoffice.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontoffice', '0008_auto_20200820_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain_type', models.CharField(choices=[('Fees', 'Fees'), ('Study', 'Study'), ('Teacher', 'Teacher'), ('Sports', 'Sports'), ('Transport', 'Transport'), ('Hostel', 'Hostel'), ('Front Site', 'Front Site'), ('Others', 'Others')], max_length=100, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(null=True)),
                ('description', models.TextField(null=True)),
                ('action_taken', models.TextField(null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='postal', validators=[frontoffice.models.validate_file])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned', to=settings.AUTH_USER_MODEL)),
                ('complain_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
