# Generated by Django 3.0.8 on 2020-08-11 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0003_auto_20200811_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('end_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_point', to='transports.Stopage')),
                ('start_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_point', to='transports.Stopage')),
            ],
        ),
    ]
