# Generated by Django 3.0.8 on 2020-08-12 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0004_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transports.Driver')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transports.Route')),
                ('vehicles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transports.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleStopage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reach_time', models.TimeField(null=True)),
                ('leave_time', models.TimeField(null=True)),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transports.Schedule')),
                ('stopage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transports.Stopage')),
            ],
        ),
    ]
