# Generated by Django 3.0.8 on 2020-08-12 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0005_schedule_schedulestopage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='vehicles',
            new_name='vehicle',
        ),
    ]
