# Generated by Django 3.0.8 on 2020-08-12 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0006_auto_20200812_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulestopage',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transports.Schedule'),
        ),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare', models.FloatField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('end_stopage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_stopage', to='transports.Stopage')),
                ('start_stopage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_stopage', to='transports.Stopage')),
            ],
        ),
    ]
