# Generated by Django 3.0.8 on 2020-08-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0007_auto_20200810_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='hostel',
        ),
        migrations.AddField(
            model_name='hostel',
            name='hostel',
            field=models.ManyToManyField(blank=True, to='hostels.Room'),
        ),
    ]
