# Generated by Django 3.0.8 on 2020-08-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0008_auto_20200810_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel',
            old_name='hostel',
            new_name='room',
        ),
    ]
