# Generated by Django 3.0.8 on 2020-08-16 09:43

import announcement.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('active_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave', validators=[announcement.models.validate_file])),
                ('apply_status', models.IntegerField(choices=[(0, 'Inactive'), (2, 'Active')], null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('nonice_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group')),
            ],
        ),
    ]
