# Generated by Django 3.0.8 on 2020-08-18 09:15

import announcement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_auto_20200818_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='holiday', validators=[announcement.models.validate_file])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
