# Generated by Django 3.0.8 on 2020-08-10 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HosteType',
            new_name='HostelType',
        ),
    ]
