# Generated by Django 3.0.8 on 2020-08-10 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0004_auto_20200810_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
                ('number_of_bed', models.IntegerField(null=True)),
                ('bed_cost', models.FloatField(null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ManyToManyField(to='hostels.Hostel')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostels.RoomType')),
            ],
        ),
    ]
