# Generated by Django 3.0.8 on 2020-08-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0005_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hostel',
            field=models.ManyToManyField(null=True, to='hostels.Hostel'),
        ),
    ]
