# Generated by Django 3.0.8 on 2020-08-11 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0011_hosteldesignation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HostelDesignation',
            new_name='Designation',
        ),
    ]
