# Generated by Django 3.0.8 on 2020-08-16 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeaveType',
            new_name='Type',
        ),
    ]
