# Generated by Django 3.0.8 on 2020-08-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0009_auto_20200809_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
