# Generated by Django 3.0.8 on 2020-08-09 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0010_auto_20200809_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('book_number', models.CharField(max_length=200, null=True)),
                ('isbn_number', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('qty', models.IntegerField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('status', models.IntegerField(null=True)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraries.Author')),
                ('book_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraries.BookLanguage')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraries.Publisher')),
                ('rack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraries.Rack')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraries.Subject')),
            ],
        ),
    ]
