# Generated by Django 3.0.8 on 2020-08-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0011_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
