# Generated by Django 3.0.8 on 2020-08-09 07:16

from django.db import migrations, models
import django.db.models.deletion
import libraries.models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0012_auto_20200809_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='', validators=[libraries.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='EBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('book_number', models.CharField(max_length=200, null=True)),
                ('isbn_number', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='', validators=[libraries.models.validate_image])),
                ('file', models.FileField(null=True, upload_to='', validators=[libraries.models.validate_file])),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraries.Author')),
                ('book_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraries.BookLanguage')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraries.Publisher')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraries.Subject')),
            ],
        ),
    ]
