# Generated by Django 3.0.8 on 2020-08-09 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import libraries.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libraries', '0013_auto_20200809_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='file',
            field=models.FileField(null=True, upload_to='ebook', validators=[libraries.models.validate_file]),
        ),
        migrations.CreateModel(
            name='BookIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('issue_date', models.DateTimeField(null=True)),
                ('return_date', models.DateTimeField(null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraries.Book')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_by', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
