# Generated by Django 3.0.8 on 2020-08-10 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libraries', '0014_auto_20200809_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissue',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
